### DISCUSSION TITLE
Tuning to produce higher quality responses

### DISCUSSION THREAD

**Discussion by Anton-V-K** [imartinez/privateGPT#1425] [Q&A]
Has anyone succeeded in tuning the engine so it produces higher quality responses?

Here is a case with the prompt
> Is 450 90% of 500?

`privateGPT` produces something like this:
> No, 450 is not 90% of 500. To find 90% of 500, you would multiply 500 by 0.9 (which represents 90% as a decimal). The result would be 450, but this means that 450 is equal to 90% of itself, not 500.
![image](https://github.com/imartinez/privateGPT/assets/20116984/67f081b8-749d-46af-bdb0-274058620af2)

I find such responses somewhat gibberish :)

For instance, GPT-4 is able to correct itself while answering same question:
![image](https://github.com/imartinez/privateGPT/assets/20116984/cac1da11-175e-4e53-87ba-f43e3e63f342)
or even give the correct answer immediately:
![image](https://github.com/imartinez/privateGPT/assets/20116984/d71002fa-1991-4a42-97f2-b65e164eb809)

Another case with Claude 2.1 (well, this engine is built on another "technology"):
![image](https://github.com/imartinez/privateGPT/assets/20116984/07ca2111-9ff1-4927-a3bf-e14c554575fb)

**Probably the engine needs extra tuning?**
I've started with defaults in `settings.yaml`:
```yaml
local:
  prompt_style: "llama2"
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.1.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5
```
