### DISCUSSION TITLE
Smaller models and options for a Nvidia Quadro P520 with only 2GB VRAM, but 384 Cuda Cores...

### DISCUSSION THREAD

**Discussion by tpiekarski** [imartinez/privateGPT#1562] [Q&A]
Hello,

I am all set up with CUDA on an Ubuntu Linux machine, but unfortunately, my Quadro P520 Mobile only has 2GB of VRAM and I remembered wrong and assumed it has 4 GB (facepalm).

And of course I am running into `ggml_backend_cuda_buffer_type_alloc_buffer: allocating 4095.05 MiB on device 0: cudaMalloc failed: out of memory`.

So I ain't have enough VRAM for the recommended model [Mistral-7B-Instruct-v0.1-GGUF](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF). 

Is there any smaller model available that I could try out (of course taking into account much worse results)?
Would there be the option to use RAM instead of VRAM but keep using GPU and Cuda Cores?
Or is CPU the only option?

Thanks in advance.

**Comment by tpiekarski** [comment]
Happen to have found [TinyLlama-1.1B-Chat-v0.3-GGUF](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF), maybe an option for me.

**Comment by tpiekarski** [comment]
Make that smaller model work. Thanks anyway :-)

I chose the TinyLama offered by The Bloke [TinyLlama-1.1B-Chat-v1.0-GGUF](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF).

The necessary changes in the settings yaml are these:
```yaml
local:
  prompt_style: "default"
  llm_hf_repo_id: TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF
  llm_hf_model_file: tinyllama-1.1b-chat-v1.0.Q5_K_S.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5
```
Should be someone interested and has only 2 GB VRAM.
