### DISCUSSION TITLE
privateGPT stuck at Generating embeddings: 0it [00:00, ?it/s]

### DISCUSSION THREAD

**Discussion by siddhsql** [imartinez/privateGPT#1911] [Q&A]
I am using v0.5.0 of privateGPT synced to this commit:

```
commit 94ef38cbba8fe5e406eb192efafe774b9aadb564 (HEAD -> mychanges, tag: v0.5.0)
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Tue Apr 2 17:45:15 2024 +0200

    chore(main): release 0.5.0 (#1708)

    Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
```

with following settings (on top of [default](https://github.com/zylon-ai/private-gpt/blob/v0.5.0/settings.yaml)):

```
server:
  env_name: ${APP_ENV:mock}

# This configuration allows you to use GPU for creating embeddings while avoiding loading LLM into vRAM
llm:
  mode: mock
  tokenizer: BAAI/bge-small-en-v1.5

# https://docs.privategpt.dev/manual/document-management/ingestion
embedding:
  mode: huggingface
  ingest_mode: batch
  count_workers: 8
```

I tried to ingest a 6MB text document using `make ingest` and got this:

```
Generating embeddings: 100%|███████████████████| 104294/104294 [04:37<00:00, 375.92it/s]
18:13:40.059 [INFO    ] private_gpt.components.ingest.ingest_component - Inserting count=104294 nodes in the index
Generating embeddings: 0it [00:00, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
Generating embeddings: 0it [00:00, ?it/s]
...
```

Its been more than half an hour and I am getting an endless scroll of 

```
Generating embeddings: 0it [00:00, ?it/s]
```

the storage in `qdrant` db keeps on increasing:

```
$ du -sh local_data/private_gpt/qdrant/collection/make_this_parameterizable_per_api_call
480M	local_data/private_gpt/qdrant/collection/make_this_parameterizable_per_api_call
```

and is already 480MB. 

what is going on here? how can I fix this?
