### DISCUSSION TITLE
How to create tiktoken cache on kubernetes

### DISCUSSION THREAD

**Discussion by Kraego** [imartinez/privateGPT#1958] [Q&A] [answered]
I try to run privategpt in a kubernetes cluster as deployment, alongside ollama. Ollama and OpenWebUI are up and running. But I've struggles with privateGPT.

**Problem:**: `PermissionError: [Errno 13] Permission denied: 'tiktoken_cache'`

I've found this solution/workaround: https://github.com/zylon-ai/private-gpt/issues/1876, which in my understanding change the uid to the uid of the host system to create the cache dir, which is not possible since kubernetes assigns a random uid to the pod.

I've changed the ownership in Dockerfile  with a `RUN chown worker /home/worker/app` Layer without success

@minixxie: I've found your question regarding running multiple replicas, how do you manage to run privateGPT in kubernetes?

below my current deployment:
````yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: privategpt
  labels:
    app: privategpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privategpt
  template:
    metadata:
      labels:
        app: privategpt
        networkrole: ingress
        spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
      - name: privategpt
        image: privategpt-image
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
            nvidia.com/gpu: "0"
        envFrom:
        - configMapRef:
            name: privategpt-config
        ports:
          - containerPort: 8001
        readinessProbe:
            tcpSocket:
              port: 8001
            timeoutSeconds: 10
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
            tcpSocket:
              port: 8001
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        volumeMounts:
        - name: privategpt-volume
          mountPath: /home/worker/app/local_data
        tty: true
      volumes:
      - name: privategpt-volume
        persistentVolumeClaim:
          claimName: privategpt-volume
```
