### ISSUE TITLE
LLM = Mock. Is this normal?

### ISSUE THREAD

**Issue by KarlTheforest** [imartinez/privateGPT#1113]
I have an issues where the privateGPT didn't response to my answer, rather leave it to blank.
<img width="926" alt="image" src="https://github.com/imartinez/privateGPT/assets/95168954/1bf7ec8b-242d-4b93-86dd-c70ba311e83a">

I have made some changes inside the directory(privateGPT) such as:

1) I create new file called `settings-openai.yaml` and **add my open api key**

2) changes settings for `settings.yaml` by **adding my openai api key**:
  ```
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /

llm:
  mode: mock

local:
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.1.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

sagemaker:
  endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140

openai:
  api_key: ${OPENAI_API_KEY: myapi key here}
```
  
  Anyone face similar issues here?
