### ISSUE TITLE
Errors when replacing default `embedding_hf_model_name`

### ISSUE THREAD

**Issue by chamaoskurumi** [imartinez/privateGPT#1117]
I'm running privateGPT locally on a server with 48 cpus, no GPU.

## Problem

When I choose a different `embedding_hf_model_name` in the `settings.yaml` than the Default `BAAI/bge-small-en-v1.5`, I run into all sorts of problems during ingestion.
I would like to replace the default `embedding_hf_model_name` (which is  `BAAI/bge-small-en-v1.5`) with some other embedding model.

_ Any ideas how to debug different embeddings models?_
_ What are the exact requirements for an embeddings model to work  with PrivateGPT?_ 

### Example 1

```
local:
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.1.Q4_K_M.gguf
  embedding_hf_model_name: hkunlp/instructor-large
```

throws the following error when trying to run it via `PGPT_PROFILES=local make run`:

`File "/.../.cache/pypoetry/virtualenvs/private-gpt-igPs2cci-py3.11/lib/python3.11/site-packages/llama_index/embeddings/huggingface.py", line 90, in ValueError: Unable to find max_length from model config. Please provide max_length`

I don't know how to debug that error - I didn't find any `max_length` parameter in files that live in the models/embedding folder nor any of the settings.ymls. :thinking: 

### Example 2

Using different llms as well...for german...

```
local:
  llm_hf_repo_id: TheBloke/Leo-Mistral-Hessianai-7B-Chat-GGUF
  llm_hf_model_file: leo-mistral-hessianai-7b-chat.Q4_K_M.gguf
  embedding_hf_model_name: T-Systems-onsite/cross-en-de-roberta-sentence-transformer
```
I tried this - all optimized for german - setup. Here I could successcully run `PGPT_PROFILES=local make run`, but I ran into a `index out of bounds` Error when trying to ingest a 100pages long pdf in German.
