### ISSUE TITLE
Error open ai embedding dimension

### ISSUE THREAD

**Issue by mrkog3** [imartinez/privateGPT#1190]
I carried out the step by step to connect open ai, I completed the installation well and I was able to connect it locally, make queries to multiple data, but when I realized that it was a little slow, I wanted to connect it to open ai, it gave me the error: chromadb.errors.InvalidDimensionException: Embedding dimension 1536 does not match collection dimensionality 384.

The key is fine and I have already created the yaml with:
```
llm:
   mode: openai

openai:
   api_key: <your_openai_api_key> #i replace with my openai key 
```

When setting the profile `$env:PGPT_PROFILES="openai"` it loads fine as:  [`INFO ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'openai']`
