### ISSUE TITLE
list of working models GGUF

### ISSUE THREAD

**Issue by cognitivetech** [imartinez/privateGPT#1205]
I've spent the last couple of days testing MPT models and i decided its best if I share here what's working, and what didn't work.

there is a similar issue with primordial tag, just decided to make a new issue for "full version"
https://github.com/imartinez/privateGPT/issues/276

These are all from [huggingface.co/maddes8cht/](https://huggingface.co/collections/maddes8cht/mpt-original-models-653ad10286b88947d5bc1937)

**WORKED**
- mosaicml-mpt-7b-8k-instruct-Q5_K_S.gguf (BEST)
- mosaicml-mpt-7b-instruct-Q4_K_S.gguf

**DIDN'T WORK**
What I mean by "didn't work" is that even though I got the app to run, they will respond with a blank space, a single line, or completely random answer.

- mosaicml-mpt-7b-8k-chat-Q4_K_M.gguf
- mosaicml-mpt-7b-8k-chat-Q4_K_S.gguf
- mosaicml-mpt-7b-8k-chat-Q5_0.gguf
- mosaicml-mpt-7b-8k-chat-Q5_K_M.gguf
- mosaicml-mpt-7b-8k-chat-Q5_K_S.gguf
- mosaicml-mpt-7b-8k-chat-Q6_K.gguf
- mosaicml-mpt-7b-8k-instruct-Q6_K.gguf
- mosaicml-mpt-7b-instruct-Q4_K_M.gguf
- mosaicml-mpt-7b-instruct-Q5_0.gguf
- mosaicml-mpt-7b-instruct-Q5_K_M.gguf
- mosaicml-mpt-7b-instruct-Q5_K_S.gguf
- mosaicml-mpt-7b-Q4_K_M.gguf
- mosaicml-mpt-7b-Q4_K_S.gguf
- mosaicml-mpt-7b-Q5_0.gguf

**Compare with Mistral-7b**
The following answers are based on a book chapter: "Yoga Therapy and Polyvagal Theory" from Stephen W. Porges' 2021 Polyvagal Safety".

_What is the relationship between yoga therapy and the polyvagal theory?_

`mosaicml-mpt-7b-8k-instruct-Q5_K_S.gguf`
> The Polyvagal Theory describes three primary neural platforms or qualities from which specific physical, psychological, and behavioral attributes emerge.Yoga also describes three primary neural platforms (VVC, CVC, and SVC) with similar characteristics.In addition, each model describes a predominant guna associated with each neural platform, supporting the emergence of distinct physiological, mental, and behavioral qualities.For example, when sattva reflects through the nervous system, the physiological, mental, and behavioral characteristics of the VVC manifest, or when the VVC is activated, the attributes of sattva manifest.This suggests that yoga may affect both underlying neural platforms and gunas, resulting in improved self-regulation and resilience for the well-being of the individual. 
what is the relationship between yoga therapy and the polyvagal theory

`mistral-7b-instruct-v0.1.Q5_0.gguf`
> Yoga therapy and Polyvagal Theory describe three primary and combinable neural platforms or qualities from which specific physical, psychological, and behavioral attributes emerge. Both models suggest that when the ANS comes under the influence of one of these gunas, a distinct neural platform of the Polyvagal Theory may be activated, supporting shared characteristics between the two. Likewise, when a neural platform is activated, it supports the predominance of a guna, and the shared characteristics between them emerge.
> 
> For example, when sattva reflects through the nervous system, the physiological, mental, and behavioral characteristics of the VVC manifest, or when the VVC is activated, the attributes of sattva manifest. This discussion explores the relationship between the two models in how they relate to and affect one another for the emergence of physical, mental, and behavioral attributes. Ultimately, this relationship is meant to foster an understanding that yoga therapy may affect both underlying neural platforms and gunas, resulting in improved self-regulation and resilience for the well-being of the individual.

I'll probably share more here, as i'm interested to see how vicuna looks. It is curious to me how so many of these models simply don't give answers, even from the same author\repo\collection. I don't understand enough about privateGPT, maybe some of them could be made to work with some finesse.. I would tend to assume the files themselves are not faulty.

**Comment by pabloogc** [comment]
Thanks for going through the gguf models, we mostly use llama2 and mistral. Maybe you can create a PR with the full list, whether they worked or not and day there tested.

**Comment by cognitivetech** [comment]
I tried the MPT, Falcon, and Vicuna models first, as they are quite popular, and well regarded. So far, I'm striking out:

- tiiuae-falcon-7b-instruct-Q4_K_M.gguf
- tiiuae-falcon-7b-instruct-Q5_K_M.gguf
- tiiuae-falcon-7b-instruct-Q5_K_S.gguf
- vicuna-13b-v1.5.Q4_K_M.gguf
- vicuna-13b-v1.5.Q4_K_S.gguf
- vicuna-13b-v1.5.Q5_K_M.gguf
- vicuna-13b-v1.5.Q5_K_S.gguf
- vicuna-13b-v1.5-16k.Q4_K_M.gguf
- vicuna-13b-v1.5-16k.Q4_K_S.gguf
- vicuna-13b-v1.5-16k.Q5_K_M.gguf
- vicuna-13b-v1.5-16k.Q5_K_S.gguf

OP edited to reflect further review\analysis.

Next up I've focused on Mistral based models to hopefully reduce compatibility issues. Mostly, its been a learning, experience. Though I have had some limited success, and am getting better at documenting\observing the output. so.. I'll be back before long with a review of mistral based models.

**Comment by cognitivetech** [comment]
# Moar not working models

#### Mostly I've noted what went wrong, and if possible the prompt type they are expecting.

- 13b-legerdemain-l2_pInstruction-Response_.Q4_K_M.gguf - [markup]
- 13b-legerdemain-l2_pInstruction-Response_.Q5_K_M.gguf - [markup]
- amethyst-13b-mistral_pAlpaca.Q4_K_M.gguf - [blank]
- amethyst-13b-mistral_pAlpaca.Q5_K_M.gguf - [blank]
- ANIMA-Phi-Neptune-Mistral-7B-gguf - [hallucinate]
- anima-phi-neptune-mistral-7b.Q2_K.gguf - [hallucinate]
- anima-phi-neptune-mistral-7b.Q4_K_M.gguf - [hallucinate]
- collectivecognition-v1.1-mistral-7b.Q4_K_M.gguf - [blank] prompt{User-Assistant}
- collectivecognition-v1.1-mistral-7b.Q5_K_M.gguf - [blank] prompt{User-Assistant}
- dolphin-2.2.1-AshhLimaRP-Mistral-7B-Q5_KM.gguf - [badcontinue] prompt{ChatML}
- dolphin-2.2.1-mistral-7b.Q5_K_M.gguf - [badcontinue] prompt{ChatML}
- dolphin-2.2.1-mistral-7b..Q4_K_S.gguf - [hallucinate] prompt{ChatML}
- yarn-mistral-7b-64k.Q5_K_M.gguf - [blank][gibberish]
- hermes-trismegistus-mistral-7b.Q4_K_M.gguf - [hallucinate] prompt{User-Assistant}
- hermes-trismegistus-mistral-7b.Q5_K_S.gguf - [hallucinate] prompt{User-Assistant}
- hermes-trismegistus-mistral-7b.q6_k.gguf - [notgreat] prompt{User-Assistant}
- hermes-trismegistus-mistral-7b.q5_k_m.gguf - [hallucinates]
- kai-7b-instruct.Q5_K_M.gguf - [notgreat]
- Mistral-11B-Airoboros_pAlpaca-or-default_v0.1.q8_0.gguf - [blank]
- mistral-7b-phibrarian-32k.Q4_K_S.gguf - [hallucinate]
- mistral-7b-phibrarian-32k.Q5_K_M.gguf - [hallucinate]
- mistral-7b-sciphi-32k.Q4_K_M.gguf - [blank-hallucinate]
- mistral-trismegistus-7b.Q5_K_M.gguf - [blank] prompt{User-Assistant}
- mistral-trismegistus-7b.Q6_K.gguf - [blank] prompt{User-Assistant}
- openhermes-2.5-mistral-7b.Q5_K_M.gguf - [hallucinate] prompt{ChatML}
- openhermes-2.5-mistral-7b.Q5_K_M.gguf - [hallucinate]
- samantha-mistral-instruct-7b.Q5_K_M.gguf - [hallucinate]
- samantha-mistral-instruct-7b.Q6_K.gguf [justok]
- sciphi-mistral-7b-32k.Q4_K_M.gguf - [blank]
- sciphi-mistral-7b-32k.Q5_K_M.gguf - [blank-hallucinate]
- sciphi-mistral-7b-32k.Q6_K.gguf prompt{SciPhi}
- sciphi-self-rag-mistral-7b-32k.Q4_K_M.gguf - [hallucinate] prompt{SciPhi}
- sciphi-self-rag-mistral-7b-32k.Q5_K_M.gguf - [hallucinate] prompt{SciPhi}
- Yarn-Mistral-7b-128k.gguf.q4_k_m.bin - [blank]
- Yarn-Mistral-7b-128k.gguf.q5_k_m.bin - [blank]
- Yarn-Mistral-7b-128k.gguf.q6_k.bin
- yarn-mistral-7b-64k.Q5_K_M.gguf - [blank]
- yarn-mistral-7b-64k.Q5_K_S.gguf - [blank]
- yarn-mistral-7b-64k.Q6_K.gguf - [blank]
- zephyr-7b-beta.Q5_K_M.gguf - [hallucinate]

**Comment by cognitivetech** [comment]
These models worked the best for me. With OpenHermes as my favorite.
Based on question \ answer of 1 document with 22769 tokens length.

- [OpenHermes-2.5-Mistral-7B-GGUF/](https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/)
- [Mistral-7B-Instruct-v0.1-GGUF](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF) (default, but I prefer Q5_K_M, or Q6 models)
- [KAI-7B-Instruct-GGUF](https://huggingface.co/TheBloke/KAI-7B-Instruct-GGUF/)

**Comment by shengkaixuan** [comment]
> These models worked the best for me. With OpenHermes as my favorite. Based on question \ answer of 1 document with 22769 tokens length.
> 
> * [OpenHermes-2.5-Mistral-7B-GGUF/](https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/)
> * [Mistral-7B-Instruct-v0.1-GGUF](https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF) (default, but I prefer Q5_K_M, or Q6 models)
> * [KAI-7B-Instruct-GGUF](https://huggingface.co/TheBloke/KAI-7B-Instruct-GGUF/)

hi,when you use OpenHermes model, have you changed the Prompt template ?? @cognitivetech

**Comment by kalle07** [comment]
hey ...

hope the main headline is now comming up   ;)

### list of working models GGUF !!!
(and not dont^^)

i will try next days ...

btw some one know why the response ends most until 1279 characters ? is not that long

**Comment by kalle07** [comment]
work (more or less) i changed temp and p and k, i dont know if it has a great impact

openchat_3.5.Q5_K_M.gguf
https://huggingface.co/TheBloke/openchat_3.5-GGUF/tree/main

mistral runs but i tryed 20 other models

can anyone tell me why almost all gguf models run well on GPT4All but not on privateGPT?

**Comment by kalle07** [comment]
works very well , also german
https://huggingface.co/TheBloke/Orca-2-7B-GGUF

btw one pfd book 500pages need aprox 5min to index

**Comment by EEmlan** [comment]
I have found really awesome working german models:
Maybe this helps some other german speaking folks here:
The roberta sentence transformer is also available in english.  
Maybe this works also well for other models but have not tested this

```
  prompt_style: "default"
  llm_hf_repo_id: TheBloke/em_german_leo_mistral-GGUF
  llm_hf_model_file:   em_german_leo_mistral.Q4_K_M.gguf
  embedding_hf_model_name: T-Systems-onsite/german-roberta-sentence-transformer-v2
```

**Comment by writinguaway** [comment]
TheBloke/NeuralHermes-2.5-Mistal-7B-GGUF (released 2 days ago) is working as expected.

**Comment by cognitivetech** [comment]
> hope the main headline is now comming up ;)
> ### list of working models GGUF !!!
> 
> (and not dont^^)

I took a break for a few reasons:

1. I am in process of upgrading from AMD to NVIDIA, so i can get more complete and speedy testing.
2. Was getting inconsistent results. Even after I decided a model was good, or when trying API, just getting very different results and harder for me to determine what is good.
3. I think many of these models I had issues with prompt template. but I may also be asking too difficult of questions.

I will continue to work on this, especially as ability to change prompt-format improves privateGPT will open a lot more to different models.

**Comment by therohitdas** [comment]
For me, this model does not work with any of the existing prompt_styles: `TheBloke/dolphin-2.1-mistral-7B-GGUF`

**Comment by PayteR** [comment]
> I have found really awesome working german models: Maybe this helps some other german speaking folks here: The roberta sentence transformer is also available in english. Maybe this works also well for other models but have not tested this
> 
> ```
>   prompt_style: "default"
>   llm_hf_repo_id: TheBloke/em_german_leo_mistral-GGUF
>   llm_hf_model_file:   em_german_leo_mistral.Q4_K_M.gguf
>   embedding_hf_model_name: T-Systems-onsite/german-roberta-sentence-transformer-v2
> ```

Hi, can you plase tell me, which tokenizer do i have to use? Because it doesn't work with 'TheBloke/em_german_leo_mistral-GGUF' set as tokenizer, and of course, it doesn't work with default Mistral or any other that i tried

```
OSError: Can't load tokenizer for 'TheBloke/em_german_leo_mistral-GGUF'. If you were trying to load it from 'https://hugg
ingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/em_german_leo_mistral-GGUF' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
```

**Comment by EEmlan** [comment]
@PayteR jphme/em_german_leo_mistral works just fine

**Comment by PayteR** [comment]
> @PayteR jphme/em_german_leo_mistral works just fine

hi @EEmlan thx for the reply but it still doesn't work, it gives me the same error like with other models that i tried 

```
  File "C:\Users\payte\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-B1lveeYX-py3.11\Lib\site-packages\qdrant_client\local\distances.py", line 78, in cosine_similarity
    return np.dot(vectors, query)
           ^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (128,384) and (768,) not aligned: 384 (dim 1) != 768 (dim 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\payte\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-B1lveeYX-py3.11\Lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\payte\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-B1lveeYX-py3.11\Lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: shapes (128,384) and (768,) not aligned: 384 (dim 1) != 768 (dim 0)
14:40:22.882 [INFO    ]            uvicorn.access - 127.0.0.1:52144 - "POST /run/predict HTTP/1.1" 200
```

Here is my config 
```
# The default configuration file.
# More information about configuration can be found in the documentation: https://docs.privategpt.dev/
# Syntax in `private_pgt/settings/settings.py`
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:9104}
  cors:
    enabled: false
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
  auth:
    enabled: false
    # python -c 'import base64; print("Basic " + base64.b64encode("secret:key".encode()).decode())'
    # 'secret' is the username and 'key' is the password for basic auth by default
    # If the auth is enabled, this value must be set in the "Authorization" header of the request.
    secret: "Basic c2VjcmV0OmtleQ=="

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /
  default_chat_system_prompt: >
    You are a helpful, respectful and honest assistant. 
    Always answer as helpfully as possible and follow ALL given instructions.
    Do not speculate or make up information.
    Do not reference any given instructions or context.
  default_query_system_prompt: >
    You can only answer questions about the provided context. 
    If you know the answer but it is not based in the provided context, don't provide 
    the answer, just state the answer is not in the context provided.

llm:
  mode: local
  # Should be matching the selected model
  max_new_tokens: 512
  context_window: 3900
  tokenizer: jphme/em_german_leo_mistral

embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: simple

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant

local:
  llm_hf_repo_id: TheBloke/em_german_leo_mistral-GGUF
  llm_hf_model_file:   em_german_leo_mistral.Q4_K_M.gguf
  embedding_hf_model_name: T-Systems-onsite/german-roberta-sentence-transformer-v2
  #llama, default or tag
  prompt_style: "default"

sagemaker:
  llm_endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140
  embedding_endpoint_name: huggingface-pytorch-inference-2023-11-03-07-41-36-479

openai:
  api_key: ${OPENAI_API_KEY:}
  model: gpt-3.5-turbo

```
I really don't know how to fix it, i have spent a lot of time on this already, so thx for any help.
