### ISSUE TITLE
Unable to query `Query Docs` mode when using sagemaker

### ISSUE THREAD

**Issue by LvffY** [imartinez/privateGPT#1367]
## Context

Hi everyone, 

I have send [a message through Discord](https://discord.com/channels/1164200432894234644/1164200433779212400/1181551995870523423) but thought it would be easier to manage the issue here.

What I'm trying to achieve is to run privateGPT with some production-grade environment. To do so, I've tried to run something like : 

- Create a Qdrant database in Qdrant cloud
- Run LLM model and embedding model through Sagemaker

For I have the following setups : 

| LLM  | Embedding | Qdrant |  State
| ------------- | ------------- | ------------- | ------------- | 
| Local | Local | Local | Success |
| Local | Local | Qdrant cloud | Success |
| Sagemaker | Local | Local | Failed |
| Sagemaker | Sagemaker | Qdrant cloud | Failed |

As we can see, whenever I'm trying to use sagemaker it seems to fail to use the RAG architecture.

## How to reproduce

I've tried to have the simplest setup to reproduce, if you want me to test anything else, do not hesitate to ask me.

- Create a new profile **sagemaker** with **settings-sagemaker.yaml** : 

```yaml
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}

ui:
  enabled: true
  path: /

llm:
  mode: sagemaker

embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: simple

sagemaker:
  llm_endpoint_name: TheBloke-Mistral-7B-Instruct-v0-1-GPTQ # This should be first deployed in your sagemaker instance
  embedding_endpoint_name: BAAI-bge-large-en-v1-5 # This should be first deployed in your sagemaker instance
```
- Ingest a file through the UI
- Run `PGPT_PROFILES=sagemaker make run`
- Ask a question related to your file. (Weirdly, if you ask a question completly unrelated it may work ...)
 
## Actual behavior

- The UI is sending a weird output
![image](https://github.com/imartinez/privateGPT/assets/37327656/a25a8f65-bd6c-4abc-89a1-eec085412b26)
- We see some weird warning related to **llama_index**
![image](https://github.com/imartinez/privateGPT/assets/37327656/3aca095c-22fb-467e-a05f-0ae12454c203)

## Expected behavior

To be able to use the `Query Docs` mode even when using sagemaker.
