### ISSUE TITLE
Tokenizer for full openai usage

### ISSUE THREAD

**Issue by felixxuss** [imartinez/privateGPT#1444]
I implemented an openai profile as follows:

```yaml
llm:
  mode: openai

openai:
  api_key: <key>
  model: "gpt-4-1106-preview" # gpt-4-1106-preview, gpt-3.5-turbo


embedding:
  mode: openai
```

My question is related to the used tokenizer. In the settings file unter llm.tokenizer I can find a link to the mistral tokenizer.
Now since I am using the openai model I was wondering if this is still the right tokenizer? Simply setting
```yaml
llm:
  tokenizer: openai
```
does not work because this is not a valid HF link. 

What can I do to use the right tokenizer when using openai models as llm and embedding model?
