### ISSUE TITLE
How to set openai org id in yaml?

### ISSUE THREAD

**Issue by greenTea2Codes** [imartinez/privateGPT#1505]
I have different organizations.

I created a openai setting yaml as mentioned at https://docs.privategpt.dev/manual/advanced-setup/llm-backends, tried to add organization so the requests bill to the correct organization:
```
openai:
  organization: <openai organization id>
  api_key: ${OPENAI_API_KEY:}
  model: gpt-3.5-turbo
```
But it doesn't pick up the org id set in the yaml.

What is the correct attribute name?
