### ISSUE TITLE
Hello, please show me how to connect this model

### ISSUE THREAD

**Issue by SyntaxEvg** [imartinez/privateGPT#1522]
Hello, please show me how to connect this model
https://huggingface.co/mlabonne/NeuralBeagle14-7B-GGUF

**Comment by SyntaxEvg** [comment]
**can you help or is this impossible?**

**Comment by sandyis** [comment]
you need to update you settings,yaml, lines 53 to 5.7 with information specific to you your Model @SyntaxEvg 
search thru other issues someone had written up how to do that 
```
local:
  prompt_style: "mistral"
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.2-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.2.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5
```
