### ISSUE TITLE
How to make PrivateGPT to translate everything into English language before store and process inputs

### ISSUE THREAD

**Issue by PayteR** [imartinez/privateGPT#1549]
Hi, I want to use PrivateGPT for Slovak documents, but it's not possible, because there is no LLM model that can work with Slovak language. I tried to make a testing python script that will 

* read the txt file
* translate it with `Helsinki-NLP/opus-mt-sk-en` into english
* summarize that english text with `Falconsai/medical_summarization` 
* translate that summarization into Slovak language with `Helsinki-NLP/opus-mt-en-sk`

And result was actually very good. So my suggestion is that PrivateGPT could have possibility to config translators so LLM and Vector database will have to work only with english text. What do you think about this? In `settings.yaml` it will be something like this 

```
translations:
  from_prompt:
    model: Helsinki-NLP/opus-mt-sk-en
    source: eng_Latn # English
    target: slk_Latn # Slovak
  from_response:
    model: Helsinki-NLP/opus-mt-en-sk # could be commented when it's same as from_prompt
    source: slk_Latn
    target: eng_Latn
  to_store:
    model: Helsinki-NLP/opus-mt-sk-en
    source: eng_Latn # English
    target: slk_Latn # Slovak
  from_store:
    model: Helsinki-NLP/opus-mt-en-sk # could be commented when it's same as to_store
    source: slk_Latn
    target: eng_Latn

```
What do you think about this? Im noob in python so i'm not really able to make it by my self, thx.
