### ISSUE TITLE
Connection to an external Qdrant instance is not working

### ISSUE THREAD

**Issue by bcatalin** [imartinez/privateGPT#1693]
Connection to an external qdrant instance is not working anymore. It was working in the last release. 

My changes in settings.yaml are:

```
vectorstore:
  database: qdrant

qdrant:
  url: http://localhost:6333
  port: 6333
  host: localhost
  https: false
```

The error message that I get when I am running make run is:
`ValueError: Only one of <location>, <url>, <host> or <path> should be specified.`

but there is no path anymore.
