### ISSUE TITLE
[QUESTION] Whats the correct settings yaml file to use with ollama-cuda ?

### ISSUE THREAD

**Issue by dealomuss** [imartinez/privateGPT#2174]
### Question

Hello,

i'm starting the app with the docker command 

`docker compose --profile ollama-cuda up
`
but when i make change in settings-ollama.yaml nothing changes. GradoUI keep using ollama and llama3.1 even if i set llm_model to mistral and embedding_model to another when

provided ui seems just to ignore any change on yml files

the only thing refering to llama cuda is in docker-compose file

```
  # Ollama service for the CUDA mode
  ollama-cuda:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - ollama-cuda
      - 
```

maybe theres a way to specify llm model and embedding model here ? because i dont see any other file setting such as settings-ollama-cuda.yml : was expecting something like that somewhere

according to the documentation the profile name here should be ollama-cuda and not just "ollama"
any tips on that ?
