### ISSUE TITLE
gpt_tokenize: unknown token ''

### ISSUE THREAD

**Issue by hajsf** [imartinez/privateGPT#328]
I'm trying to run the PrivateGPR from a docker, so I created the below:
1. Dockerfile:
```Dockerfile
# Use the python-slim version of Debian as the base image
FROM python:slim

# Update the package index and install any necessary packages
RUN apt-get update -y 
RUN apt-get install -y gcc build-essential gfortran pkg-config libssl-dev g++
RUN pip3 install --upgrade pip
RUN apt-get clean

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt and script.py files into the container
COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt --force-reinstall

COPY /script /app
COPY /models /app/models
COPY /knowledge /app/knowledge

EXPOSE 5000

# Set the default command to run when the container starts
# In this case, we're using the tail command to continuously output the contents of /dev/null
CMD ["tail", "-f", "/dev/null"]
```

2. docker-compose.yml
```yml
version: '3.8' # Specify the version of the docker-compose file format

services: # Define the services that make up your application
  app: # Name of the service
    build: # Configuration for building the Docker image for this service
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile to use
    image: my-repo/my-image-name # Name of the Docker image to use or build
    container_name: my-container-name # Name of the container to create
```

3. .env
```env
KNOWLEDGE_PATH=/app/knowledge
PERSIST_DIRECTORY=/app/db
MODEL_TYPE=GPT4All
MODEL_PATH=/app/models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L12-v2
MODEL_N_CTX=1000
```

4. Requirements.txt
```
transformers==4.29.2
torch==2.0.1
numexpr==2.8.4
langchain==0.0.171
pygpt4all==1.1.0
chromadb==0.3.23
llama-cpp-python==0.1.50
urllib3==2.0.2
pdfminer.six==20221105
flask==2.3.2
nicegui==1.2.14
streamlit==1.22.0
streamlit-extras==0.2.7
```

5. Downloaded the:
```ps1
Invoke-WebRequest -Uri "https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin" -OutFile "models\ggml-gpt4all-j-v1.3-groovy.bin"
```

6. Download the `[state_of_the_union.txt](https://github.com/imartinez/privateGPT/blob/main/source_documents/state_of_the_union.txt)` file

7. Run the below:
```bash
docker-compose up -d --build
```

The Docker image had been created succeffuly and the image had been run as well:

![image](https://github.com/imartinez/privateGPT/assets/98168280/d22f863c-bc93-461b-98d1-babc165510dd)

At the container terminal I run the below succesfuly:
```bash
# python ingest.py
# python privateGPT.py
 Enter a query: exit
```

Once I tried to enter another query, I got the error: `gpt_tokenize: unknown token ''`

![image](https://github.com/imartinez/privateGPT/assets/98168280/6092db2d-bfd0-47fe-a873-03b86f7450fb)
